// © 2026 Samskruthi Harish. Madav — Proprietary. All rights reserved. See LICENSE.
// ONE SOURCE OF TRUTH for in-app help. Powers three surfaces so they can never drift:
//   1) <HelpDot> — the "?" next to a control shows that section's { what, when }.
//   2) Sage "Explain this screen" — narrates SCREEN_HELP[mode] instantly (zero tokens).
//   3) The Tours launcher — lists each space with its blurb + guide route.
// Written at the level Madav's author explains features: what it is + when to use it.
// STANDING RULE (drift): when a screen's UI changes, update its entry here in the same
// breath — this is the human-readable companion to sage-knowledge/*.md.

// sections[].id is optional; used to anchor a HelpDot to a specific control.
export const SCREEN_HELP = {
  // ---- Workrooms (Projects) ----
  project: {
    title: "Workrooms",
    blurb: "A workroom is a project that remembers everything about itself — its instructions, its knowledge, a linked folder, a crew of agents, and goals — so every chat and mission inside it already knows the job.",
    guide: { route: "project", note: "Open Workrooms → the “Projects Guide” button in the header for the full interactive tour." },
    sections: [
      { id: "instructions", label: "Instructions", what: "The room's standing orders — tone, rules, goals.", more: "A workroom's instructions are its constitution: they're injected into every chat, every crew mission, and every scheduled run that happens inside the room, so you set the room's behaviour once instead of repeating yourself. Put the things that should always be true here — the audience, the tone of voice, hard rules, the current objective. Because they apply to the whole room, they're the fastest way to make a dozen conversations all stay on-brief.", when: "Set them once; every chat and crew mission in the room follows them automatically." },
      { id: "knowledge", label: "Knowledge shelf", what: "Notes, files and data the whole room can draw on.", more: "The knowledge shelf is the room's shared reference library — notes, files and data that every chat and agent in the room can draw on without you re-pasting it. Add the facts the room should always have at hand: pricing, specs, brand voice, key documents. Each item shows as a book-spine you can click to read or edit. Unlike an agent's personal Knowledge, this belongs to the room, so the whole crew benefits.", when: "Add the facts the room should always know — pricing, specs, brand voice. Click a book-spine to read or edit it." },
      { id: "goals", label: "Goals", what: "Checkable objectives for the project, with a progress bar.", more: "Goals turn a workroom from a chat space into a project with direction. Add checkable objectives and the room shows a progress bar and a “1/2 done” count, and the shelf banner surfaces it too — so you can see at a glance how close the room is to finished. They also give the room's own digest something concrete to report against.", when: "Track what the room is trying to achieve; the banner shows “1/2 goals” at a glance." },
      { id: "folder", label: "Linked folder & repo", what: "Where the room's file work happens.", more: "Linking a folder (or cloning a GitHub repo) gives the room a place to do real file work: any Collaborate session or file-capable agent launched from the room operates inside it. It's what connects the room's thinking to actual files on your disk, so the crew's output lands somewhere real instead of staying in chat.", when: "Link a folder (or clone a GitHub repo) so Collaborate sessions and file-tool agents operate there." },
      { id: "crew", label: "Crew", what: "Agents (and teams) staffed to this room.", more: "The crew is the set of agents — and whole teams — assigned to the room. Staffing an agent here means that when you “Put to work”, it launches already knowing the room's instructions, knowledge and folder, so it starts in context rather than cold. A room is more than a folder of chats; it's a place where your specialists are on call for this particular job.", when: "Assign specialists, then “Put to work” launches them with the room's instructions + knowledge + folder." },
      { id: "feed", label: "Work feed", what: "Every chat and mission the room produced, filterable by agent.", more: "The work feed is the room's complete history — every chat and every mission it ever produced, merged in time order and filterable by which agent did it. It's how you find anything the room made: click a row to reopen it. As the room accumulates work, this becomes the memory of what's been tried and decided here.", when: "Find anything the room ever made; click a row to reopen it." },
      { id: "playbook", label: "Room playbook", what: "Plays pinned to the room.", more: "A room playbook pins plays to the whole room, so every agent and chat working here automatically has them in hand — the team-level equivalent of an agent's signature plays. Pin a “brand voice” or “house format” play once and the entire crew applies it without anyone remembering to. As with all pins, a missing or renamed play is simply skipped, never a blocker.", when: "Pin a play (e.g. “brand voice”) and the whole crew uses it automatically here." },
      { id: "digest", label: "Digest", what: "The room writes its own summary of recent work.", more: "The digest is the room summarizing itself: click it and the room reads its own recent chats, missions and goals and writes a short “here's what's been happening, here's a sensible next step”. It's a fast way to get back up to speed on a room you haven't opened in a while, or to hand someone a status update without reading the whole feed. It needs a working model to generate.", when: "Click the document-stack icon in the header for a quick “what's been happening + next step”." },
      { id: "template", label: "Save as template", what: "Turn this room into a reusable starting point.", more: "Saving a room as a template captures its whole setup — instructions, knowledge, goals and pinned plays — as a reusable skeleton. Then “From template” on the shelf clones it into a fresh room with its own empty feed. It's how you stop rebuilding the same kind of project by hand: configure “Launch campaign” once, and spin up a clean copy for each new launch.", when: "Save a configured room, then “From template” on the shelf clones it (instructions, knowledge, goals, pins)." },
      { id: "archive", label: "Archive", what: "Hide a finished room without deleting it.", more: "Archiving tucks a finished room out of the default view without losing anything — its history, knowledge and crew are all preserved. The Active / Archived / All chips on the shelf switch what you see, and you can unarchive any time. It keeps your shelf focused on live work while keeping completed projects safe and searchable.", when: "Archive keeps the room (and its history); the shelf's Active/Archived/All chips switch what you see." },
      { id: "share", label: "Share workroom", what: "Export a .madavroom file with the room AND its crew.", more: "Sharing a workroom exports a .madavroom file that contains both the room and the agents staffed to it. When a colleague imports it, Madav recreates the room and any missing crew agents, so they get a ready-to-work setup with zero manual rebuilding. It's the difference between “here's a folder” and “here's the whole working environment”.", when: "Hand a colleague a ready-to-work room — importing recreates the room and any missing agents." },
    ],
  },
  // ---- Agents ----
  agents: {
    title: "Agents",
    blurb: "Build named specialist agents by talking to a Designer, test them on a live Bench, then put them to work solo or in teams. Each has a face, instructions, capabilities, memory and a track record.",
    guide: { route: "agents", note: "Agents → the guide opens automatically the first time, or via the “Guide” tab." },
    sections: [
      { id: "designer", label: "Designer", what: "Build or edit an agent by describing it in plain words.", more: "The Designer is where agents are born and revised, entirely by conversation — no code, no config files. You describe the agent you want (its job, how it should behave, what it can use) and the Designer assembles its blueprint: purpose, instructions, capabilities, knowledge. You can keep refining by talking (“make it stricter about sources”), and test it live before it touches real work.", when: "Use it to set the agent's purpose, instructions and capabilities — no code." },
      { id: "capabilities", label: "Capabilities", what: "The tools this agent is allowed to use. Files = read, write and edit files in the working folder. Terminal = run commands and scripts. Connectors = your linked apps (Gmail, GitHub, Slack…). Skills = use plays from your Playbook. Browser = Madav's own built-in web window (nothing to install — not Chrome). Desktop = see and control your computer's screen and apps.", more: "Capabilities are the agent's permissions — each toggle hands it one real power. They matter for both ability and safety: an agent can only touch what you switch on, so a writing agent with nothing but Skills can never run a command or open a browser. Two are commonly misread: Browser is Madav's own built-in web window for reading live pages (there is nothing to install and it is not Chrome or Safari), and Desktop lets the agent actually move the mouse and type on your screen — the most powerful toggle, and the one to grant most deliberately. Start minimal and add a capability only when a task clearly needs it.", when: "Switch on only what the job needs — a data agent wants Files + Terminal, a research agent wants Browser, a play-driven agent wants Skills. Fewer capabilities = a safer, more focused agent." },
      { id: "purpose", label: "Purpose", what: "The agent's one-line mission — who it is and what it's for.", more: "Think of it as the headline on the agent's business card. A sharp purpose keeps the agent focused: it tells the model what kind of work to accept and how to introduce itself when a session starts. Vague purposes (“a helpful assistant”) produce vague agents; concrete ones (“loads, profiles and analyzes datasets with real computed numbers”) produce agents that behave predictably.", when: "Write one clear sentence; it shapes how the agent introduces itself and what work it takes on." },
      { id: "instructions", label: "Instructions", what: "The agent's standing rules — how it thinks, its method, and its tone.", more: "This is the agent's operating manual, injected at the top of every single mission it runs — so anything you write here is always in force, not just for the next message. Describe the steps it should follow, the standards it must hold, what to do first, and what to avoid. Good instructions read like onboarding a careful new hire: “load data before estimating, run scripts so results are reproducible, present the key numbers first and the caveats last.” The more specific you are, the less the agent improvises.", when: "Be specific (e.g. \"run scripts for reproducible results, present key numbers first\"). These are injected into every mission the agent runs." },
      { id: "autonomy", label: "Autonomy", what: "How freely the agent acts on risky steps like writing files, running terminal commands, or browsing. Ask first = it pauses for your approval. Act freely = it proceeds on its own. Skip & decide = it skips anything risky and keeps going.", more: "Autonomy is the trust dial for irreversible or sensitive actions — saving over a file, running a shell command, submitting a form. “Ask first” makes the agent stop and show you each risky step for a yes/no before it acts, which is ideal while you're still learning how it behaves. “Act freely” lets it carry out those steps on its own for speed once you trust it. “Skip & decide” is the cautious middle: it avoids the risky step entirely and routes around it, finishing what it safely can. You can change this any time as your confidence grows.", when: "Use Ask first while you're still learning to trust it; switch to Act freely once you do." },
      { id: "knowledge", label: "Knowledge", what: "Files the agent ALWAYS knows — attached to every mission rather than searched. Text files (md, txt, csv, json) work best.", more: "Knowledge is the agent's permanent memory: every file here is attached in full to the start of each mission, so the agent never has to go looking for it. That makes it perfect for a handful of must-know references — a brand style guide, a data schema, a glossary. It is the wrong place for large document libraries, because attaching everything wastes the model's context and your money; for those, put the documents on a Project's knowledge shelf, where Madav retrieves only the relevant passages per task. PDFs and Word files also belong in a Project (which parses them), while images here are shown to vision-capable models.", when: "Add the few references it must never forget (a style guide, a data schema). For big document libraries or PDFs, use a Project's knowledge shelf instead — those are retrieved per task. Images are shown to vision-capable models." },
      { id: "pinnedmodel", label: "Pinned model", what: "Locks this agent to one specific model, ignoring the top-bar selector.", more: "Normally every agent runs on whatever model you've chosen in the top bar, so switching models switches all of them at once. Pinning overrides that for this one agent only — useful when an agent has a specific need: a large, strong model for an agent that does hard reasoning, or a small, fast, cheap model for one that does routine high-volume work. If you leave it unpinned the agent simply follows your live selection, which is the right default for most agents.", when: "Pin a model when the agent needs a particular strength — a large model for hard reasoning, a fast cheap one for routine work. Leave it unpinned to always use whatever you've selected live." },
      { id: "signature", label: "Signature plays", what: "Plays pinned to this agent, pre-loaded on every mission.", more: "A signature play is a skill this agent is guaranteed to have in hand — its body is loaded into the agent's instructions before every mission, so you never depend on the matcher noticing the task. Use it to give an agent its specialty moves (a researcher's source-vetting play, a writer's brand-voice play). If a pinned play is later renamed or deleted, the agent simply falls back to the normal Playbook — a missing pin never blocks a run. The agent's card shows “knows N plays” so you can see its repertoire at a glance.", when: "Give an agent its specialty moves so they're always in hand — its card reads “knows N plays”." },
      { id: "resume", label: "Résumé", what: "An agent's full profile: track record, plays, rooms, recent missions.", more: "An agent's résumé is its full profile in one place: its track record (missions run, clean rate, tokens, last active), the plays it knows, the rooms it's staffed in, and a list of recent missions you can reopen. It's how you size up a teammate before handing it bigger work — the same way you'd read a CV before assigning a project.", when: "Click the badge icon on a card to review a teammate before handing it bigger jobs." },
      { id: "coach", label: "Coach → memory", what: "👍/👎 feedback that graduates into the agent's durable memory.", more: "Coaching is how an agent learns from you over time. A thumbs-up or thumbs-down with a note (“always lead with the risks”, “drop the hype words”) doesn't just sit there — it graduates into the agent's durable memory, so the correction carries into every future mission, not just the next reply. It's the mechanism that lets an agent actually improve with use instead of repeating the same mistakes.", when: "Correct it once in the résumé (“always lead with risks”) and it sticks across every future mission." },
      { id: "presence", label: "Presence dot", what: "A status dot on the portrait: active / ready / off-duty / new.", more: "The small dot on an agent's portrait is an at-a-glance status: green if it's worked very recently, blue if within the last month, grey if it's idle or brand new. On a wall of agents it tells you which specialists are actively in rotation versus sitting unused, without opening each one.", when: "Glance to see which agents have been working recently." },
      { id: "putwork", label: "Put to work", what: "Launch the agent on a task.", more: "“Put to work” is how you deploy an agent on a real job. A file- or terminal-capable agent opens a Collaborate-style session in its folder; others open a focused chat — either way the agent starts already carrying its instructions, capabilities and any pinned plays. It's the bridge from configuring an agent to actually using it.", when: "File/terminal agents open a Collaborate folder session; others open a chat." },
      { id: "teams", label: "Teams", what: "Multiple agents working as a Relay line or a Managed (parallel) crew.", more: "Teams let several agents work together in one of two shapes. A Relay line passes the work down a chain of stages — each agent hands its output to the next — which suits jobs with clear sequential steps. A Managed crew runs agents in parallel under a coordinator, which suits jobs with independent parts. Choosing the shape is really choosing whether your work is a pipeline or a divide-and-conquer.", when: "Use a team when one job has clear stages (relay) or independent parts (managed)." },
      { id: "archetype", label: "Quick-start archetypes", what: "Pre-filled starter agents (Researcher, Writer, Analyst, Coder, Ops, Support) so you never begin from a blank form.", more: "Building an agent from nothing is intimidating to newcomers, so the Designer offers a row of strong archetypes. Click one and a complete blueprint loads — name, role, a solid set of instructions, and sensible capabilities — which you then reshape by talking to the Designer or editing the card. It's the fastest way to a good agent, and a good way to learn what a well-formed agent looks like.", when: "Start from an archetype whenever one is close to what you want; describe your own only when nothing fits." },
      { id: "vibe", label: "Personality", what: "Tone chips (Formal, Warm, Terse, Bold…) that shape how the agent writes, without you writing instructions.", more: "Non-experts can't always phrase good instructions, but everyone can pick a feel. Each chip you select is folded into a short “Tone:” line at the end of the agent's instructions, so it genuinely changes how the agent answers — not just a label. Combine a few (e.g. Warm + Thorough) to dial in a voice, and clear them to go neutral.", when: "Use it to give an agent a distinct voice quickly, or to nudge its tone after testing it on the Bench." },
      { id: "avatar", label: "Custom avatar / photo", what: "Give an agent (or a team) your own picture instead of the generated glyph.", more: "Every agent and team gets an auto-generated face (a colored glyph), but you can make them recognisable by uploading a photo — tap the camera badge on the portrait in the Designer, or on the team's avatar in the team builder. The image is downscaled and stored locally with the agent, and shows on its card, the Floor, and in teams. Tap the portrait itself to cycle the generated look instead.", when: "Upload a photo when you want agents to feel like real, distinct teammates at a glance." },
      { id: "recruiter", label: "Recruiter", what: "Describe an outcome and get a ready-made team, shown as an org chart — or start from a built-in default team.", more: "The Recruiter is the outcome-first way to build a crew: say what you want done (“find leads and send outreach”) and it proposes a named team, rendered as an org chart with the work-shape shown visually — Relay (a chain, ①→②→③) or Managed (a coordinator fanning out in parallel). Ready-made default teams load instantly without a model. A readiness line flags what the team needs on your setup (a connector to link, a folder to trust) before you hire, and “Hire this team” drops it straight onto the floor.", when: "Use the Recruiter when you know the job but not the team; pick a default team for a fast, proven starting point." },
      { id: "teamtools", label: "Team capabilities", what: "Set one capability set (Files, Terminal, Connectors, Skills, Browser, Desktop) for the whole proposed team in one place.", more: "Instead of opening each member afterwards, you can decide here what the entire team is allowed to touch before you hire. Toggling a capability applies it to every member Madav creates for this team; leave them all off to keep each member's own blueprint defaults. It's the fast way to, say, give a whole research crew the Browser, or make sure an outreach team has Connectors. You can still fine-tune any individual member later in the Designer.", when: "Use it to grant or restrict the same tools across a whole team at hire time." },
      { id: "teammodel", label: "Team model", what: "Pin one model for every member of the proposed team (optional).", more: "By default each agent runs on whatever you've selected in the top bar. Pinning here locks the whole team to one model — handy when a job needs a particular strength everywhere (a strong model for a hard analysis crew, a fast cheap one for high-volume work) without pinning each agent by hand. Leave it unpinned and every member follows your live selection. Applies to the members created for this team.", when: "Pin when the whole team should share one model; leave unpinned for normal flexibility." },
      { id: "teamautonomy", label: "Team autonomy", what: "Set how every member of the team handles risky actions in one place.", more: "Autonomy decides whether an agent pauses for your approval before risky steps (writing files, running commands, browsing). Setting it here applies the same choice to the whole team — Ask first (safe default, pauses for each risky step), Act freely (no prompts), or Skip & decide (avoids risky steps and routes around them). It saves opening each member; you can still override an individual later.", when: "Set it once for the whole crew at hire time; use Ask first until you trust the team." },
      { id: "teamplays", label: "Team signature plays", what: "Pin plays that pre-load on every member's missions.", more: "A signature play is a skill loaded into an agent's instructions before every mission. Pinning here gives the whole team the same plays in hand — a shared house style or method — without setting each agent by hand. A missing or renamed play is simply skipped, never a blocker. Members still need the Skills capability to use plays.", when: "Use it to give a whole team a shared standard (e.g. a brand-voice or house-format play)." },
      { id: "teamknowledge", label: "Team knowledge", what: "Attach files every member of the team always knows.", more: "Knowledge files are attached in full to the start of each mission. Adding them here gives the whole team the same reference material — a brief, a style guide, a schema — so every member works from the same facts. Text files (md, txt, csv, json) work best; images are shown to vision-capable models. For big document libraries, prefer a Workroom's knowledge shelf, which retrieves per task.", when: "Add the few references the entire team should never forget." },
      { id: "bench", label: "Try it (the Bench)", what: "A live rehearsal — chat with the agent you're building before you commit to it.", more: "\"Try it — interview before you hire\" opens the Bench: a test chat with the agent-in-progress, using the model you've selected. It tests only the agent's brain — its instructions and personality — with tools deliberately OFF (no Files, Terminal, Connectors or Browser), so you're judging how it thinks, answers and sounds, not its real-world actions (those switch on only after Put to work). Nothing is saved or run for real. Tweak the blueprint, then re-run your last test to compare the answer before and after. It needs a working model.", when: "Interview an agent before deploying it — ask it a representative task and see if the voice and judgement are right." },
      { id: "memory", label: "Memory", what: "Durable learnings the agent accumulates across missions — corrections, preferences, stable facts.", more: "When \"Learn across missions\" is on, after each mission the agent extracts the lasting lessons (a correction you made, a preference, a fact that won't change) and applies them next time, so it improves with use instead of repeating mistakes. You can read the notes, edit them by hand, or make it forget everything. This is where the thumbs-up/down coaching graduates into permanent behaviour. Memory is private to the agent and is never included when you export it.", when: "Check or curate it to see what an agent has internalised, or turn it off for a stateless agent." },
      { id: "trackrecord", label: "Track record", what: "The agent's real résumé — every mission it has run, with outcome, source and cost.", more: "Every time the agent works — a chat run, a team mission, a scheduled trigger, a webhook, a swarm — it's recorded here with a success/fail mark, when it happened, what kind of run it was, the rough token cost, and a one-line summary. It's how you judge whether an agent is reliable and earning its keep, rather than guessing from a single recent answer.", when: "Review it before handing an agent bigger or riskier work." },
      { id: "versions", label: "Versions", what: "Snapshots of the agent's blueprint — restore an earlier one if a change made it worse.", more: "Every time you Save in the Studio, the previous blueprint is kept (the last 10). If a tweak to the instructions or capabilities makes the agent behave worse, you can load an earlier version and Save to bring it back — non-destructive history for the agent itself, the same idea as the Studio gallery's remix safety.", when: "Use it to undo a regression, or to compare how the agent was set up before a change." },
      { id: "craft", label: "Craft — quality vs cost", what: "Optional rigor toggles that trade a little extra cost for more reliable output.", more: "The base reliability layer (plan tracking, self-repair, read-before-edit, context compaction) is always on and free. Craft adds three opt-in upgrades: Thorough mode runs one self-review pass before each final answer; Reviewer has a second model check every file change against the brief; Text-protocol tools let models without native tool-calling (most local models) still use tools. You can also set an Economy model to run the cheap helper calls (scouts, reviewer) so the rigor costs less. Each adds model calls, so turn them on when correctness matters more than speed/cost.", when: "Enable Thorough/Reviewer for high-stakes work; set Text-protocol tools when running a local model that can't call tools natively." },
      { id: "exportagent", label: "Export .agent file", what: "Save the agent as a portable file to share or back up.", more: "Exporting writes a .agent file containing the portable parts of the agent — its instructions, capabilities and knowledge — so you can hand it to a teammate or keep a backup. Two things deliberately stay behind for privacy and portability: the agent's learned Memory and its pinned model (which is specific to your providers). Importing the file recreates the agent on another setup.", when: "Use it to share an agent you built, or to back one up before a big change." },
    ],
  },
  // ---- Playbook (Skills) ----
  skills: {
    title: "Playbook",
    blurb: "Every move Madav has learned, shown as plays. Madav runs a play automatically when a task matches, or you call it with /name. Pin plays to agents and rooms so they're always in hand.",
    guide: { route: "skills", note: "Playbook → the “Playbook Guide” button: Tour, Do's & don'ts, and How to activate." },
    sections: [
      { id: "teach", label: "Teach a new play", what: "Four ways to add a play: record web, record desktop, write, import.", more: "There are four ways to add a play, in rough order of ease. Recording is the simplest: show Madav a task once on the web or your desktop and it watches, then drafts a reusable play from what you did. You can also write one by hand, or import a .madavplay someone shared. The point is you rarely start from a blank page — you demonstrate, and Madav captures the procedure.", when: "Recording is easiest — show Madav a task once and it drafts the play for your approval." },
      { id: "drafts", label: "Drafted by Madav", what: "Plays Madav drafted itself (from recordings or noticing repeated tasks).", more: "These are plays Madav drafted on its own — either distilled from a workflow you recorded, or proposed because it noticed you doing the same kind of task several times. They sit in a holding area awaiting your judgement: review one and Approve to add it to your Playbook, or Discard it. Nothing Madav drafts becomes active until you say so, so the Playbook only ever holds moves you've signed off on.", when: "Review and Approve to add them to your Playbook; Discard the rest." },
      { id: "pin", label: "Pin to agent", what: "Make a play an agent's signature move.", more: "Pinning attaches a play to a specific agent as a signature move, so its full procedure is pre-loaded on every one of that agent's missions. This removes the guesswork of automatic matching: instead of hoping Madav notices the task fits, you guarantee the agent always has that move in hand. It's how you turn a generic agent into a reliable specialist.", when: "Pinned plays pre-load on every one of that agent's missions — no relying on the matcher." },
      { id: "stats", label: "Usage line", what: "“used 12× · last by Pitchwright” on each card.", more: "Each play card carries a quiet usage line — how many times it's run and who last used it — so your Playbook becomes self-auditing. Plays that earn their keep are obvious, and a play that's gone stale gets a gentle “retire?” nudge. It turns a growing pile of plays into something you can prune with evidence rather than guesswork.", when: "See which plays earn their keep; a “retire?” chip flags dead ones." },
      { id: "chain", label: "Then run (chains)", what: "A play hands off to the plays that follow it.", more: "Chaining lets one play hand off to others when it finishes, so research → draft → format runs as a small pipeline without you building a full team. It's a lightweight way to compose moves: each play stays simple and focused, and the chain stitches them into a longer procedure. Cycles are guarded against, so a chain can't loop forever.", when: "Chain research → draft → format for a lightweight pipeline without building a team." },
      { id: "needs", label: "Needs", what: "Declare the connectors + folder a play uses.", more: "“Needs” lets a play declare the tools it depends on — particular connectors, a folder — so when the play loads, the agent gets a hint to reach for the right capabilities. It makes a play more self-describing and more likely to run correctly, because the requirements travel with it instead of living only in your head.", when: "Surfaced as a hint when the play loads, so the agent reaches for the right tools." },
      { id: "share", label: "Share play", what: "Export a .madavplay (the play + the agent that masters it).", more: "Sharing a play exports a .madavplay file that bundles the play together with the agent that's mastered it. Hand that one file to a teammate and they get both the move and the expert who knows how to use it, with no setup on their side. It's the Playbook's answer to “how do I give someone this capability, not just the instructions”.", when: "Hand a teammate a play and the expert who knows it — one file, zero setup." },
    ],
  },
  // ---- Scheduler ----
  scheduler: {
    title: "Scheduler",
    blurb: "Run agents, teams, rooms, or plays automatically — on a timer or by webhook. Source tags and folders keep a long list navigable.",
    guide: null,
    sections: [
      { id: "target", label: "Target", what: "Where a task runs: Chat, Workroom, Agent, Team, Folder, Play, or Daily brief.", more: "The target is the heart of a scheduled task — it decides what actually runs when the timer fires. A Chat target re-asks a prompt; an Agent or Team target runs that specialist on the job; a Workroom target runs inside a room (and can even “Run as” one of its crew); a Folder target does file work; a Play target runs one of your Playbook moves; a Daily brief assembles a summary. Pick the target that matches the outcome you want automated.", when: "Pick the target that matches the job; a Workroom target can also “Run as” a crew agent." },
      { id: "frequency", label: "Frequency", what: "Manual, every N minutes, daily, or weekly.", more: "Frequency is how often the task fires. Manual means it only runs when you press Play — useful for a saved one-click job. The timed options (every N minutes, daily at a time, weekly on a day) run on their own. One important caveat: scheduled tasks only fire while your computer is awake and Madav is running, so the “Keep awake” toggle exists to stop the machine sleeping through a run.", when: "Manual runs only when you press Play; the rest fire on schedule while the computer is awake." },
      { id: "filters", label: "Filter chips & tags", what: "Slice the list by Scheduled/Manual and by source, with counts.", more: "Once you have more than a handful of tasks the list gets noisy, so the filter chips let you narrow it — show only scheduled or only manual tasks, or only those of a given source (Agent, Workroom, Play…), each chip showing a count. Every task row also wears a small source tag so you can tell at a glance what kind of job it is. It's purely a navigation aid; it changes nothing about the tasks.", when: "Use them when you have many tasks; every row also wears a source tag." },
      { id: "folders", label: "Task folders", what: "Your own folders to organize tasks.", more: "Task folders are your personal filing system for the scheduler. Create a folder (say “Morning reports”) and file related tasks into it, then click its chip to see just those. They're organizational only — a task runs the same whether or not it's filed — but on a busy scheduler they keep things findable.", when: "Create a folder and file tasks into it; folder chips filter the list." },
      { id: "runs", label: "Run history", what: "Each task's last runs with status + full output.", more: "Run history is the receipt for every automated job: open it (the list icon on a task) to see each recent run with a success/fail status and the full output it produced. This is where you confirm a scheduled task is actually doing its job, and where you read what a run that fired while you were away actually returned.", when: "Open it (list icon) to read what a scheduled run produced." },
      { id: "webhooks", label: "Webhooks", what: "Fire an agent/team/task from outside (Zapier, mail, CI).", more: "Webhooks let something outside Madav trigger a task — an automation in Zapier, an incoming email rule, a CI pipeline. You POST a prompt to a local, token-protected endpoint and the matching agent/team/task runs. It's an advanced, desktop-only feature for wiring Madav into other systems; the token keeps it from being triggered by anything that doesn't have your key.", when: "POST a prompt to the local endpoint — token-protected, desktop only." },
    ],
  },
  // ---- The three work modes ----
  chat: {
    title: "Let's Chat",
    blurb: "Plain conversation with the model you've selected — the simplest surface in Madav. No folder, no agent, no mission: just you and the model, with a few power-tools built into the message bar.",
    guide: null,
    sections: [
      { id: "model", label: "Model selector", what: "The dropdown that decides which model (and therefore which provider and key) answers you.", more: "Everything in Madav runs on the model you pick here — chat, agents, Sage, Studio. The label shows the provider and the exact model string (e.g. OpenRouter · meta-llama/llama-3.3-70b-instruct). Switching it mid-conversation is fine; the next message simply uses the new model. If the status dot is grey or replies fail, this is the first place to look — it usually means the selected provider's key or model needs fixing in Model configuration.", when: "Change it when you want a stronger model for a hard question or a cheaper/faster one for casual chat." },
      { id: "mention", label: "@-mentions", what: "Type @ to pull a file or a connected app's data straight into your message.", more: "An @-mention is how you give the model something specific to look at without leaving the bar: @ a file to attach its contents, or @ a connector (Gmail, GitHub, Drive…) to let the model read from it for this message. It keeps context precise — instead of pasting a whole document, you point at it. Only connectors you've already linked appear in the list.", when: "Use it whenever your question is about a particular file or about live data in one of your apps." },
      { id: "slash", label: "/ commands", what: "Type / at the start of the bar for quick built-in actions and to run a specific play by name.", more: "Slash commands are shortcuts: they let you invoke a named play directly (/brand-voice) instead of hoping the matcher picks it, plus a handful of built-in conversation actions. It's the deliberate counterpart to automatic skill-matching — you're telling Madav exactly which move to run.", when: "Use it when you know the exact play or action you want rather than describing it." },
      { id: "skills", label: "Skills in chat", what: "Your Playbook plays apply automatically here when a task matches one.", more: "Even in plain chat, Madav watches what you ask and quietly loads a matching play from your Playbook so the answer follows that learned procedure. You don't have to do anything — but you can force a specific one with a / command, or pin plays elsewhere. If nothing matches, chat just answers normally.", when: "Rely on it for repeatable tasks you've already taught Madav; no action needed." },
      { id: "voice", label: "Voice & spoken replies", what: "The mic types what you say into the bar; spoken replies read answers aloud.", more: "The microphone button transcribes your speech directly into the message box so you can talk instead of type; it's a convenience, not a separate mode. Spoken replies (a speaker toggle) read the model's answers back to you using your computer's voice engine. Both are optional and can be switched off in Settings → Extras if you never use them.", when: "Use voice input when typing is inconvenient, and spoken replies when you'd rather listen than read." },
    ],
  },
  cowork: {
    title: "Let's Collaborate",
    blurb: "Madav working inside a real folder on your computer — reading, writing and editing files, running commands, and using your connected apps to get a job done, while you stay in control of anything risky.",
    guide: null,
    sections: [
      { id: "folder", label: "Select Folder", what: "Chooses the folder Madav is allowed to work in for this session.", more: "Collaborate always operates inside one folder you pick — that folder is its entire world, which keeps it safe and focused. The button sits on the row below the message bar, to the left of the model selector. Until you select a folder, file work can't begin; once you do, every file Madav reads, writes or edits happens there and nowhere else. Pick the project folder you actually want changed.", when: "Set it first, before describing the task — it's the one required step." },
      { id: "ask", label: "Ask Madav (task bar)", what: "Where you describe, in plain words, what you want done in the folder.", more: "This is the instruction box. Describe the outcome you want (“rename every screenshot to its date”, “fix the broken links in index.html”) and Madav plans and carries out the steps, showing its work as it goes. You don't need to spell out commands — that's its job; you describe the goal.", when: "Use it after a folder is selected to kick off the work." },
      { id: "permission", label: "Permission", what: "Controls whether Madav pauses for your approval before changing anything. Default: Ask before changes.", more: "Permission is your safety valve, set just right of the model selector. On the default “Ask before changes”, Madav stops and shows you each file write or command for a yes/no before it touches anything — nothing changes without your nod. Looser settings let it work uninterrupted for speed. Because Collaborate edits real files on your disk, start cautious and loosen only once you trust the task.", when: "Keep it on Ask before changes for unfamiliar tasks; relax it for routine, low-risk work." },
      { id: "worked", label: "Worked cards / approvals", what: "The step-by-step trail of what Madav did, with approval prompts as they come up.", more: "As Madav works, each action appears as a card and a “✓ Worked” strip builds up, so you can see exactly what happened rather than trusting a black box. When Permission is set to ask, approval prompts pop up inline — you approve or reject each risky step. It's both a live log and your control surface.", when: "Watch it during a session; approve prompts as they appear." },
      { id: "connectors", label: "Connectors here", what: "Your linked apps are available so Madav can pull in outside data while it works.", more: "Collaborate isn't limited to local files — if you've connected apps (Gmail, GitHub, Drive, Slack…), Madav can read from them as part of the job, for example pulling an issue from GitHub before editing code. Connect apps from the chat window's connector area; once linked they're available across surfaces.", when: "Use it when the task needs information that lives in one of your apps, not just the folder." },
    ],
  },
  code: {
    title: "Let's Build",
    blurb: "The same folder-based collaboration as Let's Collaborate, but tuned for software: it explores a codebase, edits files, and runs commands in a loop, and it can work directly on a connected GitHub repository.",
    guide: null,
    sections: [
      { id: "source", label: "Folder or GitHub repo", what: "Point Build at a local project folder or clone a connected GitHub repository to work on.", more: "Build needs a codebase to work in. That can be a folder already on your disk, or — if you've connected GitHub — a repository it clones for you. Either way it gets the whole project as context so it can find the right files instead of guessing. Choosing the repo/folder is the first step, just like selecting a folder in Collaborate.", when: "Set it before describing coding work; use a GitHub repo when the code lives there rather than locally." },
      { id: "loop", label: "Explore → edit → run", what: "Build's working rhythm: read the relevant code, make changes, then run it to check.", more: "Rather than blindly writing code, Build first explores the project to understand how it fits together, makes targeted edits, and then runs the code or tests to verify the change actually works — iterating if it doesn't. This is why it behaves more like a careful developer than an autocomplete: it grounds every change in the real codebase and checks its work.", when: "Trust the loop for real coding tasks — fixing bugs, adding features, refactoring." },
      { id: "terminal", label: "Terminal access", what: "Build can run shell commands — installs, builds, tests, git — as part of the work.", more: "Coding work needs a command line: installing packages, running a build, executing the test suite, running git. Build has this through the Terminal capability, so it can prove a change compiles and passes tests rather than just claiming it does. As with Collaborate, your Permission setting governs whether it runs commands freely or asks first.", when: "Expect it whenever a task involves dependencies, building, or testing." },
      { id: "permission", label: "Permission", what: "Same approval control as Collaborate — decides if Build asks before edits and commands. Default: Ask before changes.", more: "Because Build writes code and runs commands on your machine, Permission is your guardrail. On the default it pauses for approval before each file change or command; loosen it once you trust the task for an uninterrupted flow. It's the single most important safety control on this surface.", when: "Keep it strict on unfamiliar repos; relax for routine work you've done before." },
    ],
  },
  // ---- Other surfaces ----
  studio: {
    title: "Studio",
    blurb: "The make-something-by-talking surface: describe a web page, small app, diagram, game or document and Studio builds it, rendering the result live in a preview you can watch take shape and refine by conversation.",
    guide: { route: "studio", note: "Open Studio → the “Guide” tab for the full tour, do's & don'ts, and how-to recipes." },
    sections: [
      { id: "prompt", label: "Describe it (the console)", what: "The prompt box where you say what you want made, in plain language.", more: "Studio starts from a description, not a blank file. Tell it what you want (“a pricing page for madav.ai”, “a flowchart of our onboarding”, “a snake game”) and it generates the thing. You then keep talking to change it — “make the hero bolder”, “add a third column” — and it updates. The conversation is the editor.", when: "Use it to start anything visual or interactive, and to iterate on it afterwards." },
      { id: "preview", label: "Live preview", what: "The pane that renders your creation as it's built, so you see the real result immediately.", more: "Instead of describing output in text, Studio shows it — the page, diagram or app renders live beside the console and refreshes as you refine. This tight loop is the point of Studio: you see what you're getting and can react to it, rather than imagining it from a description.", when: "Watch it while iterating; it's how you judge whether a change landed." },
      { id: "build", label: "What you can build", what: "Web pages, small interactive apps, diagrams, games, and documents.", more: "Studio is deliberately broad: landing pages and UI mockups, little tools and games, flowcharts and diagrams, and document-style outputs. It's the creative front door, distinct from Let's Build (which works on a real codebase in a folder) — Studio is for conjuring a self-contained artifact quickly from a description.", when: "Reach for Studio for a quick standalone artifact; use Let's Build to work inside an existing project." },
      { id: "styles", label: "Design DNA (style presets)", what: "Save a look — palette, type and voice — as a named style and apply it to any new creation in one click.", more: "Design DNA solves the “re-describe my aesthetic every time” problem. Build something whose look you like, click “Save a look”, give it a name (e.g. “Aurora Noir”) and a short description of the palette, typography and mood, and it's stored as a preset. Select that preset before your next build and Studio applies it automatically — brand-in-a-button. A preset is really a saved prompt-prefix; it travels with every build until you switch back to “None”, and you can delete one with the × on its chip.", when: "Save a style once you've found a look worth reusing; apply it whenever you want consistency without retyping your aesthetic." },
      { id: "surprise", label: "Surprise me", what: "The dice button seeds a creative constraint into the prompt when the blank page is intimidating.", more: "A blank canvas is the enemy of creativity, and a constraint is a gift — “a dashboard as if designed by a Swiss railway in 1965” unlocks more than “make something nice”. The dice fills the prompt with one such seed; click again to reroll until something sparks, then edit it to taste before you Create.", when: "Use it when you want to make something but don't yet know what — or to break out of a rut." },
      { id: "variations", label: "Variations", what: "Ask for 1, 2 or 4 distinct takes at once, laid out side by side to compare.", more: "Designers think in options, and the worst thing a creative tool can do is force one-at-a-time. Set this to 2 or 4 and Studio produces that many distinct variations in a single comparison grid, each labeled, so you can judge them together and tell Studio which to keep refining — instead of re-asking three times and losing the ones you liked.", when: "Turn it up when you're exploring a direction; keep it at 1 take once you know what you want." },
      { id: "crew", label: "Crew mode", what: "Runs a Concept → Critic → Polish pass so the idea is refined before you see it.", more: "Crew mode puts a small studio team on your idea: a Concept pass sketches the approach, a Critic pass names the weaknesses, and a Polish pass fixes them into the final result. You see the three short notes and then the refined artifact — creativity as a visible relay rather than a black box. It costs a little more thinking time for a more considered first draft.", when: "Switch it on for important or ambiguous pieces where a self-critique improves the result; leave it off for quick one-offs." },
      { id: "gallery", label: "Gallery", what: "Your saved creations — reopen, remix, download, or send them onward, instead of losing them to chat history.", more: "Every great artifact normally scrolls away. The Gallery makes your output an asset you return to: click “Save to gallery” on any preview and it's kept here as a thumbnail. Reopen it any time to view it full-size, “Refine in Studio” to remix it (the original stays safe — that's how lineage works), Download it, or remove it. It turns Studio from a one-shot generator into a body of work.", when: "Save anything you might want again; browse the Gallery to reuse or build on past work." },
      { id: "export", label: "Export & send onward", what: "From any preview: save to gallery, download the file, or send it to a Workroom's knowledge shelf.", more: "Creation is only half the loop — the output has to go somewhere. Beyond download and copy, the artifact's toolbar can send a finished piece straight to a Workroom's knowledge shelf, where your crew can build on it (a pitch mock becomes a room's reference; a component becomes a team's starting point). It's how Studio output feeds back into the rest of Madav instead of staying trapped on the canvas.", when: "Use it when a creation is done and needs to live somewhere — a workroom, a file, or your gallery." },
    ],
  },
  models: {
    title: "Model configuration",
    blurb: "Where you connect the AI providers that power everything in Madav. You bring your own keys (or a free/local model); Madav stores each provider as a profile and lets you pick which one runs from the top bar.",
    guide: null,
    sections: [
      { id: "provider", label: "Provider profile", what: "A saved connection to one AI provider — its key, address, and models.", more: "Madav doesn't host models; it talks to providers you connect. Each provider card is a profile holding everything needed to reach that service. OpenRouter is the easiest first stop — a single key unlocks hundreds of models, including free ones. You can keep several providers configured at once and switch between them from the top-bar selector.", when: "Add a profile for each service you want to use — OpenRouter, OpenAI, a local server, etc." },
      { id: "key", label: "API key", what: "Your personal credential authorizing Madav to use that provider on your account.", more: "The key is how the provider knows the requests are yours and bills your account. You paste it once into the provider card and Madav stores it locally on your machine — it is never sent anywhere except to that provider. Free options exist (OpenRouter free models, or a local model with no key at all), so you can start without spending anything.", when: "Paste it when adding a provider; replace it if the provider rejects requests (a 401/403 error)." },
      { id: "baseurl", label: "Base URL", what: "The provider's address — only change it for self-hosted or non-standard endpoints.", more: "Most providers have a default address Madav already knows, so you can leave this alone. It exists for the cases that need it: a local model server (like Ollama or LM Studio) on your own machine, or an OpenAI-compatible gateway at a custom address. If you're using a mainstream cloud provider, the default is correct.", when: "Only touch it when pointing Madav at a local server or a custom-hosted endpoint." },
      { id: "modellist", label: "Saved model list", what: "The set of models from a provider you've saved so they appear in the selector.", more: "A provider may offer hundreds of models; this is where you curate the ones you actually use so the top-bar selector stays short and relevant. Save the few you care about (a strong one, a fast one, a cheap one) rather than wading through the full catalogue each time.", when: "Edit it when you want to add a newly released model or trim ones you never pick." },
      { id: "backup", label: "Backup & restore", what: "Export your whole configuration to a file, or import it back.", more: "Your providers, keys, saved models and settings represent real setup effort, so Madav lets you export them as a backup file and restore them later — handy when moving to a new machine or before a big change. Keep the backup file safe, since it contains your keys.", when: "Export before reinstalling or switching computers; import to bring your setup across." },
    ],
  },
  connectors: {
    title: "Connectors",
    blurb: "How Madav reaches your other apps — Gmail, GitHub, Slack, Drive and many more — so agents and chat can read and act on the data that lives in them, all over the open MCP standard.",
    guide: null,
    sections: [
      { id: "what", label: "What a connector is", what: "A live link to an external app that exposes that app's actions to Madav as tools.", more: "A connector turns an outside service into something Madav can use directly: once Gmail is connected, an agent can read your mail; once GitHub is connected, it can open issues or read code. Under the hood this uses MCP (Model Context Protocol), an open standard for exposing an app's capabilities to AI — which is why the same mechanism works for dozens of different services.", when: "Connect an app whenever you want Madav to use real data or actions from it, not just talk about it." },
      { id: "add", label: "Connecting an app", what: "Add a connector from the registry, or paste a custom MCP server command.", more: "Madav offers a searchable registry of ready-made connectors plus featured one-click presets for common needs; for anything custom you can point Madav at any MCP server. Connecting usually means authorizing the app once. After that the connector is available everywhere — chat @-mentions, agent capabilities, and Collaborate sessions.", when: "Do it once per app you rely on; you won't need to repeat it each session." },
      { id: "tools", label: "Tools a connector exposes", what: "The specific actions a connected app makes available — read, send, search, create.", more: "Each connector brings a set of concrete tools rather than vague “access”. Gmail might expose read, search and draft; GitHub might expose list-issues, read-file and create-issue. An agent uses these the way it uses files or the terminal, and you can see exactly what an app can do before relying on it. Granular tools keep things predictable and safe.", when: "Check a connector's tools when you want to know precisely what an agent could do with it." },
      { id: "usage", label: "Where connectors are used", what: "Connected apps are available in chat (@-mention) and to any agent with the Connectors capability.", more: "A connector isn't tied to one screen: @-mention it in chat for a one-off, or switch on an agent's Connectors capability so it can reach that app on every mission. This is how a workroom crew can, say, pull from GitHub and post to Slack as part of a single job — the connectors are shared plumbing for the whole app.", when: "Reference them in chat for quick lookups; grant the Connectors capability for agents that need them routinely." },
    ],
  },
  scheduler_brief: null,
  consumption: {
    title: "Consumption",
    blurb: "Your usage dashboard — how many tokens you've used over time, which models you lean on, your activity streaks, and an estimate of what it's costing — so the “bring your own key” model never holds surprises.",
    guide: null,
    sections: [
      { id: "tokens", label: "Tokens over time", what: "A chart of how much you've sent to and received from models across days.", more: "Tokens are the unit models bill in, so this trend is the clearest picture of your actual usage. It shows whether your consumption is steady, spiking, or growing — useful for spotting a runaway scheduled task or an unusually heavy day before it shows up on a provider bill.", when: "Check it to understand your usage pattern or to investigate an unexpected jump." },
      { id: "share", label: "Model share", what: "A breakdown of which models did what proportion of your work.", more: "Because different models cost very differently, knowing the split matters: it tells you whether your spend is going to an expensive model you could swap for routine work, or whether free/local models are carrying their weight. It turns “I use a few models” into concrete proportions.", when: "Review it when deciding whether to move routine work onto a cheaper model." },
      { id: "spend", label: "Estimated spend", what: "An approximate cost of your usage, based on each model's pricing.", more: "Madav can't see your real provider invoice, but it estimates cost by applying known per-token pricing to your usage, giving you a running sense of spend without logging into each provider. Treat it as a close estimate, not an exact bill — promotions, free tiers and pricing changes mean the provider's number is final.", when: "Use it as an early-warning gauge; confirm exact figures with your provider." },
    ],
  },
  terminal: {
    title: "Terminal",
    blurb: "A real command-line terminal built into Madav, plus a standalone Madav CLI you can install to drive the same engine from any folder on your computer.",
    guide: null,
    sections: [
      { id: "inapp", label: "In-app terminal", what: "A working shell inside Madav for running commands yourself.", more: "This is a genuine terminal embedded in the app — handy for quick commands without leaving Madav, and for seeing the same environment agents use when they run shell commands. It complements the agent surfaces: agents can run commands for you, but sometimes you just want to type one yourself.", when: "Use it for quick manual commands or to inspect the environment agents operate in." },
      { id: "cli", label: "Madav CLI", what: "A standalone command-line tool that runs Madav's engine from any folder.", more: "Beyond the in-app terminal, you can install the Madav CLI so the same engine is available directly in your own terminal, in any project folder — useful if you live on the command line and want Madav's help without switching to the desktop app. It's the same brain, different doorway.", when: "Install it if you prefer working from your own terminal in arbitrary folders." },
    ],
  },
  viamobile: {
    title: "Via Mobile",
    blurb: "A bridge that lets you drive Madav from your phone over Telegram — send a task from anywhere and it runs on your desktop, with the reply coming back to your chat.",
    guide: null,
    sections: [
      { id: "setup", label: "Telegram link", what: "Pairs your phone's Telegram with Madav on your computer.", more: "Via Mobile works by connecting a Telegram chat to your running desktop Madav. Once paired, messages you send from your phone are received and acted on by the desktop app — so the heavy lifting still happens on your computer with your keys and folders, and you're just remote-controlling it. Telegram is the courier, not the engine.", when: "Set it up once so you can reach Madav while away from your desk." },
      { id: "use", label: "Driving a session remotely", what: "Send a prompt or task from your phone; the desktop runs it and replies.", more: "After pairing you can fire off work from anywhere — kick off a task, ask a question, check on something — and the desktop processes it and sends results back to your Telegram. It's designed for nudging work along when you're mobile, not for doing folder-heavy editing from a tiny screen.", when: "Use it to start or check on work when you're away from the computer." },
    ],
  },
  settings: {
    title: "Settings",
    blurb: "Where you make Madav yours — light/dark theme and accent colour, your account and workspace, links to model configuration, and the Extras switches that turn optional features on or off.",
    guide: null,
    sections: [
      { id: "theme", label: "Theme", what: "Switches Madav between light and dark appearance.", more: "A straightforward light/dark choice for comfort and environment. Madav is carefully styled for both — dark for low-light focus, light for bright rooms — and the whole app, including these help popovers, follows your pick.", when: "Set it to match your lighting and preference." },
      { id: "accent", label: "Accent colour", what: "Sets the highlight colour used across buttons, links and active states — including multi-colour accents drawn from the Madav logo.", more: "The accent is the single colour that ties the interface together. Beyond the presets you can build a custom one, choose a warm terracotta, or generate a multi-colour accent sampled from the Madav logo's own gradient — so the app can feel personal or on-brand. It's purely visual and changes nothing about behaviour.", when: "Change it whenever you want a different look or a brand-matched palette." },
      { id: "account", label: "Account & workspace", what: "Your login and the agents, teams and folders that follow it.", more: "Your account anchors your workspace — sign in and your agents, teams and task folders come with you, so the same setup is there across sessions and machines. This is also where account-level details live.", when: "Use it to sign in, review your account, or confirm your workspace is synced." },
      { id: "extras", label: "Extras (feature switches)", what: "Toggles for optional features like voice input, spoken replies, and learned-skill drafting.", more: "Not every feature suits every user, so Madav keeps the optional ones behind switches here — voice input, spoken replies, automatic skill-forging from your habits, and similar. Turn off what you don't use to keep the interface lean; turn things on to opt into more automation. Nothing here is required for the core app to work.", when: "Visit it to enable a feature you want or silence one you don't." },
    ],
  },
};

// The Tours launcher reads these — each space + where its guide lives.
export const TOURS = [
  { id: "project", title: "Workrooms", blurb: "Projects that remember — instructions, knowledge, crew, goals." },
  { id: "agents", title: "Agents", blurb: "Build specialists, give them plays, review their résumés." },
  { id: "skills", title: "Playbook", blurb: "Teach reusable plays; pin them everywhere they should run." },
  { id: "scheduler", title: "Scheduler", blurb: "Run agents, rooms, and plays on a timer." },
  { id: "studio", title: "Studio", blurb: "Make things by talking — pages, tools, games, diagrams. Save looks, explore variations, keep a gallery." },
];

// What's new — surfaced in the Tours launcher so people discover recent additions.
export const WHATS_NEW = [
  { t: "Studio creative suite", d: "Design DNA style presets, Variations, Crew mode (Concept→Critic→Polish), a Gallery, Surprise-me seeds, and a Studio Guide.", go: "studio" },
  { t: "Designer & Recruiter redesign", d: "A living agent card with archetype starters, personality, and custom photos; the Recruiter proposes ready-made teams as an org chart.", go: "agents" },
  { t: "Pinned plays everywhere", d: "Pin a play to an agent (signature move) or a room (team standard); chains, needs, usage stats, and .madavplay sharing.", go: "skills" },
  { t: "Workroom goals, templates & archive", d: "Track objectives, save a room as a template, archive finished ones, and let a room write its own digest.", go: "project" },
  { t: "Agent résumé & coaching", d: "A full profile per agent — track record, plays, rooms — and a thumbs up/down that graduates into its memory.", go: "agents" },
  { t: "Multi-color accents", d: "Settings → Appearance: the Madav logo gradient, a warm terracotta, or build your own.", go: "settings" },
];

export function screenHelp(mode) { return SCREEN_HELP[mode] || null; }
