// © 2026 Samskruthi Harish. Madav — Proprietary. All rights reserved. See LICENSE.
// Exposes window.madav — the real Bridge (mirrors src/bridge/contract.js).
const { contextBridge, ipcRenderer } = require("electron");

const listeners = new Set();
ipcRenderer.on("madav:event", (_e, uiEvent) => {
  listeners.forEach((cb) => cb(uiEvent));
});

contextBridge.exposeInMainWorld("madav", {
  // --- Bridge contract ---
  start: (req) => ipcRenderer.invoke("madav:start", req),
  sendInput: (sessionId, text, images) => ipcRenderer.invoke("madav:sendInput", { sessionId, text, images }),
  interrupt: (sessionId) => ipcRenderer.invoke("madav:interrupt", { sessionId }),
  setPermissionMode: (sessionId, mode) => ipcRenderer.invoke("madav:setPermissionMode", { sessionId, mode }),
  resolvePermission: (requestId, result) => ipcRenderer.send("madav:resolvePermission", { requestId, result }),
  onEvent: (cb) => { listeners.add(cb); return () => listeners.delete(cb); },

  // --- settings / models ---
  getSettings: () => ipcRenderer.invoke("madav:getSettings"),
  ensurePythonTools: () => ipcRenderer.invoke("madav:ensurePythonTools"),
  saveSettings: (next) => ipcRenderer.invoke("madav:saveSettings", next),
  listModels: (profileId) => ipcRenderer.invoke("madav:listModels", profileId),
  pingProvider: (profileId) => ipcRenderer.invoke("madav:pingProvider", profileId),

  // --- account / sign-in ---
  saveAccount: (account) => ipcRenderer.invoke("madav:saveAccount", account),
  signOut: () => ipcRenderer.invoke("madav:signOut"),
  googleSignIn: () => ipcRenderer.invoke("madav:googleSignIn"),
  githubSignIn: () => ipcRenderer.invoke("madav:githubSignIn"),

  // --- agent ---
  chooseFolder: () => ipcRenderer.invoke("madav:chooseFolder"),
  listDir: (dir) => ipcRenderer.invoke("madav:listDir", dir),
  openExternal: (url) => ipcRenderer.invoke("madav:openExternal", url),
  openPath: (p) => ipcRenderer.invoke("madav:openPath", p),
  saveAndOpen: (name, b64, dir) => ipcRenderer.invoke("madav:saveAndOpen", { name, b64, dir }),
  showInFolder: (p) => ipcRenderer.invoke("madav:showInFolder", p),

  // --- model speed check ---
  runSpeedTest: (args) => ipcRenderer.invoke("madav:runSpeedTest", args),
  cancelSpeedTest: () => ipcRenderer.invoke("madav:cancelSpeedTest"),
  getSpeedTestLast: () => ipcRenderer.invoke("madav:getSpeedTestLast"),
  getSpeedTestStatus: () => ipcRenderer.invoke("madav:getSpeedTestStatus"),
  getOpenRouterCatalog: (opts) => ipcRenderer.invoke("madav:getOpenRouterCatalog", opts),

  // --- persisted chat history (Talk / Collaborate / Build) ---
  listSessions: (mode, agentScope) => ipcRenderer.invoke("madav:listSessions", mode, agentScope),
  searchSessions: (q, mode) => ipcRenderer.invoke("madav:searchSessions", { q, mode }),
  getAppVersion: () => ipcRenderer.invoke("madav:getAppVersion"),
  qaStart: () => ipcRenderer.invoke("madav:qaStart"),
  qaStatus: () => ipcRenderer.invoke("madav:qaStatus"),
  qaHistory: () => ipcRenderer.invoke("madav:qaHistory"),
  qaDiagnose: (test) => ipcRenderer.invoke("madav:qaDiagnose", test),
  qaApplyFix: (fix) => ipcRenderer.invoke("madav:qaApplyFix", fix),
  qaRollback: (args) => ipcRenderer.invoke("madav:qaRollback", args),
  onQaEvent: (cb) => { const h = (_e, m) => cb(m); ipcRenderer.on("madav:qa", h); return () => ipcRenderer.removeListener("madav:qa", h); },
  recordDesktopStart: () => ipcRenderer.invoke("madav:recordDesktopStart"),
  recordDesktopStop: () => ipcRenderer.invoke("madav:recordDesktopStop"),
  recordDesktopStatus: () => ipcRenderer.invoke("madav:recordDesktopStatus"),
  librarianStatus: () => ipcRenderer.invoke("madav:librarianStatus"),
  librarianScan: () => ipcRenderer.invoke("madav:librarianScan"),
  librarianGenerate: (areaFile) => ipcRenderer.invoke("madav:librarianGenerate", areaFile),
  librarianProposals: () => ipcRenderer.invoke("madav:librarianProposals"),
  librarianApply: (areaFile) => ipcRenderer.invoke("madav:librarianApply", areaFile),
  librarianDiscard: (areaFile) => ipcRenderer.invoke("madav:librarianDiscard", areaFile),
  librarianRollback: (args) => ipcRenderer.invoke("madav:librarianRollback", args),
  forgeList: () => ipcRenderer.invoke("madav:forgeList"),
  forgeApprove: (name) => ipcRenderer.invoke("madav:forgeApprove", name),
  forgeDiscard: (name) => ipcRenderer.invoke("madav:forgeDiscard", name),
  recordFlowStart: () => ipcRenderer.invoke("madav:recordFlowStart"),
  recordFlowStop: () => ipcRenderer.invoke("madav:recordFlowStop"),
  recordFlowStatus: () => ipcRenderer.invoke("madav:recordFlowStatus"),
  getSession: (id) => ipcRenderer.invoke("madav:getSession", id),
  deleteSession: (id) => ipcRenderer.invoke("madav:deleteSession", id),
  renameSession: (id, title) => ipcRenderer.invoke("madav:renameSession", { id, title }),

  // --- saved library (bookmarked responses) ---
  listSaved: () => ipcRenderer.invoke("madav:listSaved"),
  saveResponse: (item) => ipcRenderer.invoke("madav:saveResponse", item),
  updateSaved: (id, patch) => ipcRenderer.invoke("madav:updateSaved", { id, patch }),
  removeSaved: (id) => ipcRenderer.invoke("madav:removeSaved", id),

  // --- connectors (MCP) ---
  testConnector: (server) => ipcRenderer.invoke("madav:testConnector", server),
  connectorSignIn: (server) => ipcRenderer.invoke("madav:connectorSignIn", server),
  connectorAuthStatus: (serverId) => ipcRenderer.invoke("madav:connectorAuthStatus", serverId),
  connectorSignOut: (serverId) => ipcRenderer.invoke("madav:connectorSignOut", serverId),
  listConnectorDirectory: (opts) => ipcRenderer.invoke("madav:listConnectorDirectory", opts),

  // --- skills ---
  listSkills: () => ipcRenderer.invoke("madav:listSkills"),
  createSkill: (name) => ipcRenderer.invoke("madav:createSkill", name),
  importSkillFolder: () => ipcRenderer.invoke("madav:importSkillFolder"),
  importSkillZip: () => ipcRenderer.invoke("madav:importSkillZip"),
  readSkill: (dir) => ipcRenderer.invoke("madav:readSkill", dir),
  setSkillEnabled: (dir, enabled) => ipcRenderer.invoke("madav:setSkillEnabled", { dir, enabled }),
  deleteSkill: (dir) => ipcRenderer.invoke("madav:deleteSkill", dir),
  setPinnedSkills: (context, contextId, skillNames) => ipcRenderer.invoke("madav:setPinnedSkills", { context, contextId, skillNames }),
  getPlayStats: () => ipcRenderer.invoke("madav:getPlayStats"),
  exportPlay: (skillName) => ipcRenderer.invoke("madav:exportPlay", skillName),
  importPlay: () => ipcRenderer.invoke("madav:importPlay"),
  setPlayChain: (name, chain) => ipcRenderer.invoke("madav:setPlayChain", { name, chain }),
  setPlayNeeds: (name, connectors, folder) => ipcRenderer.invoke("madav:setPlayNeeds", { name, connectors, folder }),
  getPlayConfig: () => ipcRenderer.invoke("madav:getPlayConfig"),
  setTeamPinnedSkills: (teamId, skillNames) => ipcRenderer.invoke("madav:setTeamPinnedSkills", { teamId, skillNames }),
  getPinSuggestions: () => ipcRenderer.invoke("madav:getPinSuggestions"),

  // --- projects ---
  listProjects: () => ipcRenderer.invoke("madav:listProjects"),
  getProject: (id) => ipcRenderer.invoke("madav:getProject", id),
  createProject: (name) => ipcRenderer.invoke("madav:createProject", name),
  updateProject: (id, patch) => ipcRenderer.invoke("madav:updateProject", { id, patch }),
  deleteProject: (id) => ipcRenderer.invoke("madav:deleteProject", id),
  assignProjectAgent: (projectId, agentId) => ipcRenderer.invoke("madav:assignProjectAgent", { projectId, agentId }),
  unassignProjectAgent: (projectId, agentId) => ipcRenderer.invoke("madav:unassignProjectAgent", { projectId, agentId }),
  getProjectAgentHistory: (projectId) => ipcRenderer.invoke("madav:getProjectAgentHistory", projectId),
  assignProjectTeam: (projectId, teamId) => ipcRenderer.invoke("madav:assignProjectTeam", { projectId, teamId }),
  unassignProjectTeam: (projectId, teamId) => ipcRenderer.invoke("madav:unassignProjectTeam", { projectId, teamId }),
  seedSampleFiles: (dir) => ipcRenderer.invoke("madav:seedSampleFiles", dir),
  addKnowledgeText: (projectId, name, content) => ipcRenderer.invoke("madav:addKnowledgeText", { projectId, name, content }),
  addKnowledgeFile: (projectId) => ipcRenderer.invoke("madav:addKnowledgeFile", projectId),
  removeKnowledge: (projectId, knId) => ipcRenderer.invoke("madav:removeKnowledge", { projectId, knId }),
  linkProjectFolder: (projectId) => ipcRenderer.invoke("madav:linkProjectFolder", projectId),
  linkGithub: (projectId, url) => ipcRenderer.invoke("madav:linkGithub", { projectId, url }),
  cloneRepo: (url) => ipcRenderer.invoke("madav:cloneRepo", url),
  pullGithub: (projectId) => ipcRenderer.invoke("madav:pullGithub", projectId),
  unlinkProjectSource: (projectId) => ipcRenderer.invoke("madav:unlinkProjectSource", projectId),
  listConversations: (projectId) => ipcRenderer.invoke("madav:listConversations", projectId),
  getConversation: (id) => ipcRenderer.invoke("madav:getConversation", id),
  createConversation: (projectId) => ipcRenderer.invoke("madav:createConversation", projectId),
  deleteConversation: (id) => ipcRenderer.invoke("madav:deleteConversation", id),
  renameConversation: (id, title) => ipcRenderer.invoke("madav:renameConversation", id, title),

  // --- agent engine: memory · track record · missions · versions · swarms · webhooks ---
  getAgentMemory: (agentId) => ipcRenderer.invoke("madav:getAgentMemory", agentId),
  setAgentMemory: (agentId, notes) => ipcRenderer.invoke("madav:setAgentMemory", { agentId, notes }),
  clearAgentMemory: (agentId) => ipcRenderer.invoke("madav:clearAgentMemory", agentId),
  getAgentHistory: (agentId) => ipcRenderer.invoke("madav:getAgentHistory", agentId),
  getAgentStats: () => ipcRenderer.invoke("madav:getAgentStats"),
  getMission: (convId) => ipcRenderer.invoke("madav:getMission", convId),
  exportAgent: (agent) => ipcRenderer.invoke("madav:exportAgent", agent),
  importAgent: () => ipcRenderer.invoke("madav:importAgent"),
  snapshotAgentVersion: (agent) => ipcRenderer.invoke("madav:snapshotAgentVersion", agent),
  listAgentVersions: (agentId) => ipcRenderer.invoke("madav:listAgentVersions", agentId),
  applyWebhooks: () => ipcRenderer.invoke("madav:applyWebhooks"),
  webhookStatus: () => ipcRenderer.invoke("madav:webhookStatus"),
  newWebhookToken: () => ipcRenderer.invoke("madav:newWebhookToken"),
  transcribe: (args) => ipcRenderer.invoke("madav:transcribe", args),
  winSpeech: (args) => ipcRenderer.invoke("madav:winSpeech", args),
  getModelStats: () => ipcRenderer.invoke("madav:getModelStats"),
  getUserMemory: () => ipcRenderer.invoke("madav:getUserMemory"),
  setUserMemory: (notes) => ipcRenderer.invoke("madav:setUserMemory", notes),
  clearUserMemory: () => ipcRenderer.invoke("madav:clearUserMemory"),
  runSwarm: (args) => ipcRenderer.invoke("madav:runSwarm", args),
  cancelSwarm: (swarmId) => ipcRenderer.invoke("madav:cancelSwarm", swarmId),
  onSwarmEvent: (cb) => { const h = (_e, m) => cb(m); ipcRenderer.on("madav:swarm", h); return () => ipcRenderer.removeListener("madav:swarm", h); },

  // --- background + scheduled tasks ---
  listTasks: () => ipcRenderer.invoke("madav:listTasks"),
  createTask: () => ipcRenderer.invoke("madav:createTask"),
  updateTask: (id, patch) => ipcRenderer.invoke("madav:updateTask", { id, patch }),
  deleteTask: (id) => ipcRenderer.invoke("madav:deleteTask", id),
  getRuns: (id) => ipcRenderer.invoke("madav:getRuns", id),
  runTaskNow: (id) => ipcRenderer.invoke("madav:runTaskNow", id),

  // --- usage ---
  getUsage: (days) => ipcRenderer.invoke("madav:getUsage", days),

  // --- run tracing + alerts (observability) ---
  getTraces: (limit) => ipcRenderer.invoke("madav:getTraces", limit),
  getTrace: (id) => ipcRenderer.invoke("madav:getTrace", id),
  getTraceSummary: (days) => ipcRenderer.invoke("madav:getTraceSummary", days),
  clearTraces: () => ipcRenderer.invoke("madav:clearTraces"),
  testAlert: () => ipcRenderer.invoke("madav:testAlert"),

  // --- messaging (Telegram) ---
  applyMessaging: () => ipcRenderer.invoke("madav:applyMessaging"),
  messagingStatus: () => ipcRenderer.invoke("madav:messagingStatus"),
  completeOnce: (messages) => ipcRenderer.invoke("madav:completeOnce", messages),
  listViaMobile: () => ipcRenderer.invoke("madav:listViaMobile"),
  removeViaMobile: (id) => ipcRenderer.invoke("madav:removeViaMobile", id),
  clearViaMobile: () => ipcRenderer.invoke("madav:clearViaMobile"),
  authSignIn: (provider) => ipcRenderer.invoke("madav:authSignIn", provider),
  authMe: () => ipcRenderer.invoke("madav:authMe"),
  authSignOut: () => ipcRenderer.invoke("madav:authSignOut"),
  billingCheckout: () => ipcRenderer.invoke("madav:billingCheckout"),
  billingPortal: () => ipcRenderer.invoke("madav:billingPortal"),
  track: (type, meta) => ipcRenderer.invoke("madav:track", type, meta),
  adminStats: (adminKey) => ipcRenderer.invoke("madav:adminStats", adminKey),
  adminUsers: (adminKey) => ipcRenderer.invoke("madav:adminUsers", adminKey),
  adminSearchUsage: (adminKey) => ipcRenderer.invoke("madav:adminSearchUsage", adminKey),
  adminAction: (id, action, adminKey) => ipcRenderer.invoke("madav:adminAction", id, action, adminKey),
  scoreQuiz: (batch) => ipcRenderer.invoke("madav:scoreQuiz", batch),
  apiCall: (method, path, body) => ipcRenderer.invoke("madav:apiCall", method, path, body),
  enableCli: () => ipcRenderer.invoke("madav:enableCli"),
  cliStatus: () => ipcRenderer.invoke("madav:cliStatus"),
  disableCli: () => ipcRenderer.invoke("madav:disableCli"),
  termCreate: (opts) => ipcRenderer.invoke("madav:termCreate", opts),
  termInput: (id, data) => ipcRenderer.invoke("madav:termInput", { id, data }),
  termResize: (id, cols, rows) => ipcRenderer.invoke("madav:termResize", { id, cols, rows }),
  termKill: (id) => ipcRenderer.invoke("madav:termKill", id),
  onTermData: (cb) => { const h = (_e, m) => cb(m); ipcRenderer.on("madav:term:data", h); return () => ipcRenderer.removeListener("madav:term:data", h); },
  onTermExit: (cb) => { const h = (_e, m) => cb(m); ipcRenderer.on("madav:term:exit", h); return () => ipcRenderer.removeListener("madav:term:exit", h); },
  getMobileLink: () => ipcRenderer.invoke("madav:getMobileLink"),
  setMobileLink: (link) => ipcRenderer.invoke("madav:setMobileLink", link),
  clearMobileLink: () => ipcRenderer.invoke("madav:clearMobileLink"),
  setKeepAwake: (on) => ipcRenderer.invoke("madav:setKeepAwake", on),
});
