// core/agent-rules.js — ESM SINGLE SOURCE for cross-surface agent prompt rules (ADR-0001 core migration).
// Imported by: web/renderer + server natively; desktop (electron/*.cjs) via dynamic await import().
// The data-tools rule differs BY EXECUTION MODEL (desktop shell+Node vs web Pyodide-only) — ONE source,
// the adapter's capabilities select the right text. Each branch is byte-identical to the prior per-surface copy.
const DESKTOP_DATA_TOOLS = " DATA & SPREADSHEETS: when a task means processing data files (xlsx/csv) or producing an office file, PREFER writing and running a Python script with run_bash (pandas + openpyxl) — let code do the joins and the math; do NOT compute large aggregations by hand. NEVER name a script after a Python standard-library module (inspect.py, code.py, test.py, json.py, string.py, random.py, etc.) — it shadows the stdlib and breaks pandas with a 'partially initialized module / circular import' error; use a unique name like build_report.py. If Python is unavailable, use Node instead — it is ALWAYS available: write a uniquely-named .js script and run it with \"node build_report.js\"; the exceljs library is bundled (const ExcelJS = require(\"exceljs\")) for reading and writing .xlsx. read_file already returns spreadsheets as readable rows. CRITICAL \u2014 the file must contain REAL DATA, not formula text: compute the numbers in Python and write the actual VALUES into the cells. Do NOT put Excel formula strings (text starting with '=') into a pandas DataFrame and then call df.to_excel() \u2014 pandas saves them as TEXT, so Excel shows \"=...\" literally and the sheet has NO usable numbers. Write the computed values; if you truly need live formulas, set them via openpyxl cell assignment (ws[\"B2\"] = \"=...\" or ws.cell(row,col).value = ...), NEVER through a DataFrame of '=' strings. Before finishing, sanity-check that every data cell holds a number, not a '=' string. When you produce a spreadsheet, document, deck, or PDF, deliver it as ONE officedoc block so the user gets a card to open and download it right here.";
const WEB_DATA_TOOLS = `You CAN run Python in the browser with run_python (pandas + openpyxl available) — use it for DATA work: read the project files by name (e.g. pandas.read_excel("Backlog.xlsx")), compute, and write the result (e.g. an .xlsx report) back into the folder. Let Python do the joins and math rather than computing by hand. There is no system shell or pip — only run_python. NEVER name a script or output file after a Python standard-library module (inspect/code/test/json/random/string) — it breaks imports.`;
// caps.shell === true  -> desktop (run_bash + Node + exceljs);  otherwise -> web (run_python / Pyodide, no shell).
export function dataToolsRule(caps = {}) { return caps && caps.shell ? DESKTOP_DATA_TOOLS : WEB_DATA_TOOLS; }

// Web-search answer guidance — ONE source for web + desktop (was a desktop-only `webSearchNote` string
// plus a separate web copy). Tells the model to actually search and answer FULLY with the source cited,
// which is what gave desktop its richer answers. Byte-identical to the prior desktop string.
export const SEARCH_ANSWER_RULE = "You can search the web: call the web_search tool for anything current or beyond your training data — news, latest releases, prices, 'today'/'now', recent events. Do NOT say you cannot access the internet or browse; search first, then answer with what you find and cite the sources.";
