// core/agent-rules.js — ESM SINGLE SOURCE for cross-surface agent prompt rules (ADR-0001 core migration).
// Imported by: web/renderer + server natively; desktop (electron/*.cjs) via dynamic await import().
// The data-tools rule differs BY EXECUTION MODEL (desktop shell+Node vs web Pyodide-only) — ONE source,
// the adapter's capabilities select the right text. Each branch is byte-identical to the prior per-surface copy.
const DESKTOP_DATA_TOOLS = " DATA & SPREADSHEETS: when a task means processing data files (xlsx/csv) or producing an office file, PREFER writing and running a Python script with run_bash (pandas + openpyxl) — let code do the joins and the math; do NOT compute large aggregations by hand. NEVER name a script after a Python standard-library module (inspect.py, code.py, test.py, json.py, string.py, random.py, etc.) — it shadows the stdlib and breaks pandas with a 'partially initialized module / circular import' error; use a unique name like build_report.py. If Python is unavailable, use Node instead — it is ALWAYS available: write a uniquely-named .js script and run it with \"node build_report.js\"; the exceljs library is bundled (const ExcelJS = require(\"exceljs\")) for reading and writing .xlsx. read_file already returns spreadsheets as readable rows. CRITICAL \u2014 the file must contain REAL DATA, not formula text: compute the numbers in Python and write the actual VALUES into the cells. Do NOT put Excel formula strings (text starting with '=') into a pandas DataFrame and then call df.to_excel() \u2014 pandas saves them as TEXT, so Excel shows \"=...\" literally and the sheet has NO usable numbers. Write the computed values; if you truly need live formulas, set them via openpyxl cell assignment (ws[\"B2\"] = \"=...\" or ws.cell(row,col).value = ...), NEVER through a DataFrame of '=' strings. Before finishing, sanity-check that every data cell holds a number, not a '=' string. For a SPREADSHEET, the deliverable is the .xlsx file you SAVE with the script (Madav shows the open/download card automatically) — do NOT hand-write an officedoc spreadsheet spec for anything beyond a trivial table, since that breaks on complex multi-sheet models. When you produce a Word document, deck, or PDF instead, deliver THAT as ONE officedoc block so the user gets a card to open and download it right here.";
const WEB_DATA_TOOLS = `You CAN run Python in the browser with run_python (pandas + openpyxl available) — use it for DATA work: read the project files by name (e.g. pandas.read_excel("Backlog.xlsx")), compute, and write the result (e.g. an .xlsx report) back into the folder. Let Python do the joins and math rather than computing by hand. There is no system shell or pip — only run_python. NEVER name a script or output file after a Python standard-library module (inspect/code/test/json/random/string) — it breaks imports.`;
// caps.shell === true  -> desktop (run_bash + Node + exceljs);  otherwise -> web (run_python / Pyodide, no shell).
const SPREADSHEET_CRAFT = ` BUILDING A SPREADSHEET (especially a multi-sheet or financial model — projections, unit economics, LTV/CAC, cohorts, budgets, P&L): do the WHOLE calculation in Python FIRST, holding running values in plain variables and looping over the periods (months or years), then write the finished NUMBERS into the cells. This is the reliable way — build it this way every time. Put ALL the work in ONE uniquely-named script (never named after a Python module like json/random/string/code/test/inspect, which shadows the stdlib and breaks pandas), run it ONCE, then stop — don't spread the work across many separate commands, don't keep re-inspecting the data, and never end your turn until the .xlsx is saved. NEVER write an Excel formula that points at its own cell or at a still-blank cell — that creates a circular reference and broken numbers, the #1 cause of a wrong model. Put assumptions/inputs on their OWN sheet; on each output sheet write the COMPUTED VALUES. Prefer real computed values over live '=' formulas; add live formulas only when the user explicitly asks, and then point each one ONLY at cells that already hold numbers, never at itself. Make it look finished with openpyxl: a bold header row, sensible number formats (#,##0 · $#,##0 · 0.0% · multiples like 2.7x), column widths, and a sheet title. Before saving, double-check: every data cell holds a number (not a '=' string), each total adds up, and every ratio (for example LTV:CAC) divides the correct two cells, and display a ratio with its real value (e.g. 2.98x) rather than rounding it to a flattering whole number. If the user asks for a chart, graph, trend or visualization, add a NATIVE Excel chart with openpyxl (build a LineChart or BarChart and bind it to the data with openpyxl.chart.Reference, then ws.add_chart) — a real embedded chart, not a picture; But the SPREADSHEET ITSELF IS THE PRIORITY: SAVE the workbook FIRST, then add the chart — and if the chart code gives you any trouble or errors, save the file WITHOUT the chart rather than producing nothing. NEVER let the chart block the deliverable. (Charts need openpyxl/Python; exceljs cannot make them, so use Python when a chart is asked for.) Save ONE uniquely-named .xlsx and report the file name. `;
export function dataToolsRule(caps = {}) { return (caps && caps.shell ? DESKTOP_DATA_TOOLS : WEB_DATA_TOOLS) + SPREADSHEET_CRAFT; }

// Does this user turn warrant the data/script path (run code that builds or works a spreadsheet)? SINGLE
// SOURCE for desktop (session-manager _turn) + web (Let's Chat). Triggers on EXPLICIT spreadsheet vocabulary
// (rare in plain chat) OR an analyse-my-files request; deliberately excludes ambiguous words
// (report/model/data/table) so normal conversation, writing, and Q&A stay on the fast plain-chat path.
export function needsDataTools(text) {
  const t = String(text || "").toLowerCase();
  if (/\b(xlsx|xlsm|\.xls\b|excel|spreadsheet|workbook|\.csv\b|csv|pivot table)\b/.test(t)) return true;
  if (/\b(analy[sz]e|process|aggregate|reconcile|summari[sz]e|tabulate|crunch)\b/.test(t)
      && /\b(these files|the files|my data|the data|uploaded|attached|source files|raw data|dataset)\b/.test(t)) return true;
  return false;
}

// Web-search answer guidance — ONE source for web + desktop (was a desktop `webSearchNote` string + a
// separate web copy). Make the model actually search, answer fully, and cite REAL results only — the
// anti-fabrication clause stops models inventing plausible-looking URLs/sources to satisfy "cite a source".
export const SEARCH_ANSWER_RULE = "You can search the web: call the web_search tool for anything current or beyond your training data — news, latest releases, prices, 'today'/'now', recent events. Do NOT say you cannot access the internet or browse; search first, then answer with what you ACTUALLY found, preferring the most recent result. Cite ONLY a source that appears in your search results and copy its real URL exactly — NEVER invent, guess, or reconstruct a URL, headline, outlet, or date. If the search returns nothing useful, say so plainly instead of making something up.";
