"""EdgeTrader reflector — closes the learning loop.

Scans decisions/decision-log.md for `pending` entries whose horizon has elapsed,
computes the realized return and alpha vs the benchmark (yfinance), rewrites the
entry with the outcome, and appends a lesson to decisions/lessons.md.

Lessons are generated by the ET Chief Strategist agent via the Madav webhook
(so the same judge that decided also reflects); if Madav isn't running, a
factual template lesson is written instead.

The batch runner injects recent decisions + lessons into every new mission brief,
so lessons change future verdicts — that's the memory.

Usage:  python reflector.py
"""
from __future__ import annotations

import json
import re
import sys
import urllib.request
from datetime import date, datetime, timedelta
from pathlib import Path

try:  # Windows pipes default to cp1252 — keep ✓/α printable when run by the scheduler
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

ROOT = Path(__file__).resolve().parent
CFG = json.loads((ROOT / "config.json").read_text(encoding="utf-8"))

ROW = re.compile(r"^\|\s*(\d{4}-\d{2}-\d{2})\s*\|\s*([A-Z0-9.\-]+)\s*\|\s*([A-Z ]+?)\s*\|\s*(\d+)\s*\|\s*pending\s*\|\s*$")


def realized(ticker: str, decision_date: str, horizon: int, benchmark: str):
    """Return (resolved, ticker_ret_pct, bench_ret_pct, alpha_pct)."""
    import yfinance as yf
    start = datetime.strptime(decision_date, "%Y-%m-%d")
    end = start + timedelta(days=horizon + 7)

    def leg(sym):
        h = yf.Ticker(sym).history(start=start.strftime("%Y-%m-%d"), end=end.strftime("%Y-%m-%d"),
                                   interval="1d", auto_adjust=True)
        if h is None or h.empty:
            raise ValueError(f"no data for {sym}")
        closes = [float(x) for x in h["Close"].tolist()]
        done = len(closes) - 1 >= horizon
        exit_i = min(horizon, len(closes) - 1)
        return (closes[exit_i] / closes[0] - 1) * 100, done

    rt, done_t = leg(ticker)
    rb, done_b = leg(benchmark)
    return (done_t and done_b), round(rt, 2), round(rb, 2), round(rt - rb, 2)


def llm_lesson(ticker, ddate, verdict, conviction, ret, bench, alpha) -> str | None:
    """Ask the ET Chief Strategist (via webhook) for a 2-3 sentence lesson."""
    wh = CFG.get("webhook", {})
    if not (wh.get("token") and wh.get("base_url")):
        return None
    prompt = (
        f"Reflection request (not a new analysis — do NOT call tools, do NOT output a verdict block).\n"
        f"On {ddate} you rated {ticker} {verdict} with conviction {conviction}/10, horizon {CFG.get('horizon_days', 5)} trading days.\n"
        f"Realized: {ticker} {ret:+.2f}%, {CFG.get('benchmark','SPY')} {bench:+.2f}%, alpha {alpha:+.2f}%.\n"
        f"Write ONE durable lesson (2-3 sentences) future analyses should apply: was the call right for the right reasons, "
        f"wrong, or right by luck? Be concrete about WHAT signal was over/under-weighted. Reply with the lesson only."
    )
    try:
        req = urllib.request.Request(
            f"{wh['base_url'].rstrip('/')}/hook/agent/agent_et_chief",
            data=json.dumps({"prompt": prompt}).encode(), method="POST",
            headers={"Authorization": "Bearer " + wh["token"], "Content-Type": "application/json"})
        with urllib.request.urlopen(req, timeout=300) as r:
            body = json.loads(r.read().decode() or "{}")
        text = str(body.get("output") or "").strip()
        return text[:600] if text else None
    except Exception:
        return None


def main():
    log_f = ROOT / CFG["decision_log"]
    if not log_f.exists():
        print("no decision log yet — nothing to reflect on")
        return
    lessons_f = ROOT / CFG["lessons_file"]
    lessons_f.parent.mkdir(parents=True, exist_ok=True)
    horizon = int(CFG.get("horizon_days", 5))
    benchmark = CFG.get("benchmark", "SPY")

    lines = log_f.read_text(encoding="utf-8").splitlines()
    resolved_count = 0
    new_lessons = []
    for i, line in enumerate(lines):
        m = ROW.match(line.strip())
        if not m:
            continue
        ddate, ticker, verdict, conviction = m.group(1), m.group(2), m.group(3).strip(), int(m.group(4))
        # horizon in TRADING days — require horizon + buffer calendar days before resolving
        age = (date.today() - datetime.strptime(ddate, "%Y-%m-%d").date()).days
        if age < horizon + 2:
            continue
        try:
            done, ret, bench, alpha = realized(ticker, ddate, horizon, benchmark)
        except Exception as e:
            print(f"  ! {ticker} {ddate}: {e}")
            continue
        if not done:
            continue
        outcome = f"{ret:+.2f}% (α {alpha:+.2f}% vs {benchmark})"
        lines[i] = line.replace("| pending |", f"| {outcome} |")
        resolved_count += 1
        directional = "BUY" in verdict
        won = (alpha > 0) if directional else (alpha < 0) if "SELL" in verdict else abs(alpha) < 1.5
        lesson = llm_lesson(ticker, ddate, verdict, conviction, ret, bench, alpha) or (
            f"{ddate} {ticker} {verdict} (conviction {conviction}) realized {outcome} — "
            f"{'call beat the benchmark' if won else 'call did not beat the benchmark'}; "
            f"review what the analysis over/under-weighted before the next {ticker} verdict."
        )
        new_lessons.append(f"- [{date.today().isoformat()} · {ticker} · {verdict} → α {alpha:+.2f}%] {lesson}")
        print(f"  ✓ {ticker} {ddate}: {outcome}")

    if resolved_count:
        log_f.write_text("\n".join(lines) + "\n", encoding="utf-8")
        header_needed = (not lessons_f.exists()) or lessons_f.stat().st_size == 0
        with open(lessons_f, "a", encoding="utf-8") as f:
            if header_needed:
                f.write("# EdgeTrader lessons (auto-generated by reflector.py)\n\n")
            f.write("\n".join(new_lessons) + "\n")
        print(f"\nresolved {resolved_count} decision(s); {len(new_lessons)} lesson(s) appended")
    else:
        print("no pending decisions past their horizon")


if __name__ == "__main__":
    main()
